[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "cmake",
  "ninja; platform_system!='Windows'",
  "numpy>=2.0",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
markers = [
  "integration: marks tests that exercise integration between solver components",
  "parallel: check that starts multiple worker processes",
]
